name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:      # allows manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render backend
        run: curl -s https://portfolio-zbe2.onrender.com > /dev/null
